# Generated by Django 5.0.6 on 2024-06-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('energy_consumption', models.FloatField(help_text='Energy consumption in kWh')),
                ('meat_consumption', models.FloatField(help_text='Amount of meat consumed in kg per week')),
                ('travel_distance', models.FloatField(help_text='Distance traveled by car in km per week')),
                ('waste_production', models.FloatField(help_text='Waste produced in kg per week')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
