# Generated by Django 4.2 on 2024-06-13 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carbon_footprint_website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfootprint",
            name="user_name",
        ),
        migrations.AddField(
            model_name="userfootprint",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carbon_footprint_userfootprints",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userfootprint",
            name="energy_consumption",
            field=models.FloatField(help_text="Energy consumption in kWh per week"),
        ),
    ]
